#include "PSTypes.h"

namespace Rad {

	DF_ENUM_BEGIN(PS_BillboardType)
		DF_ENUM(POINT)
		DF_ENUM(ORIENTED)
		DF_ENUM(ORIENTED_COMMON)
		DF_ENUM(PERPENDICULAR)
		DF_ENUM(PERPENDICULAR_COMMON)
	DF_ENUM_END()

	
	DF_ENUM_BEGIN(PS_BlendMode)
		DF_ENUM(OPACITY)
		DF_ENUM(ADD)
		DF_ENUM(ALPHA_BLEND)
		DF_ENUM(COLOR_BLEND)
	DF_ENUM_END()

	DF_ENUM_BEGIN(PS_Operation)
		DF_ENUM(SET)
		DF_ENUM(ADD)
		DF_ENUM(SUB)
		DF_ENUM(MUL)
		DF_ENUM(AVG)
	DF_ENUM_END()

}