#include "MTypes.h"

namespace Rad {

	//
	DF_ENUM_BEGIN(eCullMode)
		DF_ENUM(NONE)
		DF_ENUM(FRONT)
		DF_ENUM(BACK)

		DF_ENUM(INHERIT)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eFillMode)
		DF_ENUM(POINT)
		DF_ENUM(FRAME)
		DF_ENUM(SOLID)

		DF_ENUM(INHERIT)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eBlendMode)
		DF_ENUM(OPACITY)
		DF_ENUM(ALPHA_TEST)
		DF_ENUM(ALPHA_BLEND)
		DF_ENUM(ADD)
		DF_ENUM(MUL)
		DF_ENUM(COLOR_BLEND)

		DF_ENUM(INHERIT)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eDepthMode)
		DF_ENUM(NONE)
		DF_ENUM(ALWAYS)

		DF_ENUM(EQUAL)
		DF_ENUM(LESS)
		DF_ENUM(LESS_EQUAL)
		DF_ENUM(GREATER)
		DF_ENUM(GREATER_EQUAL)

		DF_ENUM(N_EQUAL)
		DF_ENUM(N_LESS)
		DF_ENUM(N_LESS_EQUAL)
		DF_ENUM(N_LESS_EQUAL)
		DF_ENUM(N_GREATER)
		DF_ENUM(N_GREATER_EQUAL)

		DF_ENUM(INHERIT)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eColorMode)
		DF_ENUM(NONE)
		DF_ENUM(RED)
		DF_ENUM(GREEN)
		DF_ENUM(BLUE)
		DF_ENUM(ALPHA)
		DF_ENUM(ALL)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eLightType)
		DF_ENUM(POINT)
		DF_ENUM(DIRECTION)
		DF_ENUM(SPOT)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eStaticLightingMode)
		DF_ENUM(NONE)
		DF_ENUM(LIGHTING_COLOR)
		DF_ENUM(LIGHTING_MAP)
	DF_ENUM_END()

}