#include "MTypes.h"

namespace Rad {

	//
	DF_ENUM_BEGIN(eCullMode)
		DF_ENUM(NONE)
		DF_ENUM(FRONT)
		DF_ENUM(BACK)

		DF_ENUM(INHERIT)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eFillMode)
		DF_ENUM(POINT)
		DF_ENUM(FRAME)
		DF_ENUM(SOLID)

		DF_ENUM(INHERIT)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eBlendMode)
		DF_ENUM(OPACITY)
		DF_ENUM(ALPHA_TEST)
		DF_ENUM(ALPHA_BLEND)
		DF_ENUM(ADD)
		DF_ENUM(MUL)
		DF_ENUM(COLOR_BLEND)

		DF_ENUM(INHERIT)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eDepthMode)
		DF_ENUM(NONE)
		DF_ENUM(ALWAYS)

		DF_ENUM(EQUAL)
		DF_ENUM(LESS)
		DF_ENUM(LESS_EQUAL)
		DF_ENUM(GREATER)
		DF_ENUM(GREATER_EQUAL)

		DF_ENUM(N_EQUAL)
		DF_ENUM(N_LESS)
		DF_ENUM(N_LESS_EQUAL)
		DF_ENUM(N_LESS_EQUAL)
		DF_ENUM(N_GREATER)
		DF_ENUM(N_GREATER_EQUAL)

		DF_ENUM(INHERIT)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eColorMode)
		DF_ENUM(NONE)
		DF_ENUM(RED)
		DF_ENUM(GREEN)
		DF_ENUM(BLUE)
		DF_ENUM(ALPHA)
		DF_ENUM(ALL)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eSamplerBindType)
		DF_ENUM(NONE)
		DF_ENUM(EMISSIVE)
		DF_ENUM(DIFFUSE)
		DF_ENUM(SPECULAR)
		DF_ENUM(NORMAL)
		DF_ENUM(LIGHTING_MAP)

		DF_ENUM(EXTERN0)
		DF_ENUM(EXTERN1)
		DF_ENUM(EXTERN2)
		DF_ENUM(EXTERN3)

		DF_ENUM(SAMPLER)
		DF_ENUM(SPECIAL)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eSPType)
		DF_ENUM(FLOAT1)
		DF_ENUM(FLOAT2)
		DF_ENUM(FLOAT3)
		DF_ENUM(FLOAT4)
		DF_ENUM(MATRIX4)

		DF_ENUM(WORLD_MATRIX)
		DF_ENUM(VIEW_MATRIX)
		DF_ENUM(PROJ_MATRIX)
		DF_ENUM(WORLD_VIEW_MATRIX)
		DF_ENUM(VIEW_PROJ_MATRIX)
		DF_ENUM(WORLD_VIEW_PROJ_MATRIX)
		DF_ENUM(BONE_MATRIX)

		DF_ENUM(CAMERA_POSITION)
		DF_ENUM(CAMERA_RIGHT_VECTOR)
		DF_ENUM(CAMERA_UP_VECTOR)
		DF_ENUM(CAMERA_DIR_VECTOR)

		DF_ENUM(LIGHT_POSITION)
		DF_ENUM(LIGHT_DIRECTION)
		DF_ENUM(LIGHT_ATTEN_PARAM)
		DF_ENUM(LIGHT_SPOT_PARAM)
		DF_ENUM(LIGHT_AMBIENT)
		DF_ENUM(LIGHT_DIFFUSE)
		DF_ENUM(LIGHT_SPECULAR)

		DF_ENUM(MATERIAL_EMISSIVE)
		DF_ENUM(MATERIAL_AMBIENT)
		DF_ENUM(MATERIAL_DIFFUSE)
		DF_ENUM(MATERIAL_SPECULAR)

		DF_ENUM(EMISSIVE)
		DF_ENUM(AMBIENT)
		DF_ENUM(DIFFUSE)
		DF_ENUM(SPECULAR)
		DF_ENUM(OPACITY)

		DF_ENUM(FOG_COLOR)
		DF_ENUM(FOG_PARAM)

		DF_ENUM(SHADER_STATE)

		DF_ENUM(TIME)

		DF_ENUM(CLIP_PLANE)

		DF_ENUM(USER_CONST)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eTexAddress)
		DF_ENUM(WRAP)
		DF_ENUM(MIRROR)
		DF_ENUM(CLAMP)
		DF_ENUM(BORDER)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eTexFilter)
		DF_ENUM(DEFAULT)
		DF_ENUM(POINT)
		DF_ENUM(LINEAR)
		DF_ENUM(ANISOTROPIC)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eVertexSemantic)
		DF_ENUM(POSITION)
		DF_ENUM(NORMAL)
		DF_ENUM(COLOR)
		DF_ENUM(LIGHTING_COLOR)

		DF_ENUM(BONE_INDEX)
		DF_ENUM(BONE_WEIGHT)

		DF_ENUM(TEXCOORD0)
		DF_ENUM(TEXCOORD1)
		DF_ENUM(TEXCOORD2)
		DF_ENUM(TEXCOORD3)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eVertexType)
		DF_ENUM(BYTE1)
		DF_ENUM(BYTE2)
		DF_ENUM(BYTE3)
		DF_ENUM(BYTE4)

		DF_ENUM(UBYTE1)
		DF_ENUM(UBYTE2)
		DF_ENUM(UBYTE3)
		DF_ENUM(UBYTE4)

		DF_ENUM(SHORT1)
		DF_ENUM(SHORT2)
		DF_ENUM(SHORT3)
		DF_ENUM(SHORT4)

		DF_ENUM(USHORT1)
		DF_ENUM(USHORT2)
		DF_ENUM(USHORT3)
		DF_ENUM(USHORT4)

		DF_ENUM(FLOAT1)
		DF_ENUM(FLOAT2)
		DF_ENUM(FLOAT3)
		DF_ENUM(FLOAT4)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eLightType)
		DF_ENUM(POINT)
		DF_ENUM(DIRECTION)
		DF_ENUM(SPOT)
	DF_ENUM_END()

	//
	DF_ENUM_BEGIN(eStaticLightingMode)
		DF_ENUM(NONE)
		DF_ENUM(LIGHTING_COLOR)
		DF_ENUM(LIGHTING_MAP)
	DF_ENUM_END()

}